spring.application.name=mediaSequencerJava
spring.datasource.url=jdbc:mysql://localhost:3306/media_sequencer
spring.datasource.username=root
spring.datasource.password=Nikhil@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
